name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish
    - name: Zip Files
    - uses: actions/checkout@v2
    - uses: papeloto/action-zip@v1
      with:
        files: /home/runner/work/Lab05/Lab05/Lab05/bin/Debug/net5.0/publish/
        dest: release.zip
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: publish
        path: ./publish
       
