name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish
    - name: Decompress
      uses: TonyBogdanov/zip@1.0
      with:
        args: zip -qq -r publish.zip . -i /home/runner/work/Lab05/Lab05/Lab05/bin/Debug/net5.0/publish
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: upload
        # A file, directory or wildcard pattern that describes what to upload
        path: publish.zip
    - name: Has Permission
      # You may pin to the exact commit or the version.
      # uses: scherermichael-oss/action-has-permission@847b08d7fdb9eaa8b19a1dab0fff385997d74f99
      uses: scherermichael-oss/action-has-permission@1.0.5
      with:
        # Required permission level (read, write, admin)
        required-permission: read
    - name: Download artifact
  # You may pin to the exact commit or the version.
  # uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
      uses: aochmann/actions-download-artifact@1.0.4
      with:
        # GitHub token
        github_token: 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   # optional, default is ${{github.token}}
        # Repository name with owner
        #repo: # optional, default is ${{github.repository}}
        # Artifact name (download all artifacts in not specified)
        name: upload
        # Download latest artifact
        #latest: # optional
        # Artifact unpack location
        #path: # optional, default is ./
       
