name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish
    - name: Decompress
      uses: TonyBogdanov/zip@1.0
      with:
        args: zip -qq -r publish.zip . -i /home/runner/work/Lab05/Lab05/Lab05/bin/Debug/net5.0/publish
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: upload
        # A file, directory or wildcard pattern that describes what to upload
        path: publish.zip
    - name: Has Permission
      # You may pin to the exact commit or the version.
      # uses: scherermichael-oss/action-has-permission@847b08d7fdb9eaa8b19a1dab0fff385997d74f99
      uses: scherermichael-oss/action-has-permission@1.0.5
      with:
        # Required permission level (read, write, admin)
        required-permission: read
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        # Artifact name
        name: upload
        # Destination path
        path: ./
       
